# Secrets for PRODUCTION - JWT
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: criptojackpot
type: Opaque
stringData:
  JWT_SECRET_KEY: "VMKPqxgcrp8JUgUFqUUuEOg4z89ErxwvBv5J9BFANVCQWJIH3wwmfl6J7CKwdNNf"
  JWT_ISSUER: "CryptoJackpotIdentity"
  JWT_AUDIENCE: "CryptoJackpotApp"
