# Secrets for PRODUCTION - MongoDB (DigitalOcean Managed)
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  namespace: criptojackpot
type: Opaque
stringData:
  MONGODB_ROOT_USERNAME: "doadmin"
  MONGODB_ROOT_PASSWORD: "0957n86PVGgm3J2D"
  MONGODB_AUDIT_CONNECTION: "mongodb+srv://doadmin:0957n86PVGgm3J2D@private-criptojackpot-prod-mongodb-1249f9b8.mongo.ondigitalocean.com/admin?authSource=admin&replicaSet=criptojackpot-prod-mongodb&tls=true"
  MONGODB_AUDIT_DATABASE: "criptojackpot_audit"
