# Secrets for PRODUCTION - Redis/Valkey (DigitalOcean Managed)
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: criptojackpot
type: Opaque
stringData:
  REDIS_CONNECTION_STRING: "private-criptojackpot-prod-redis-do-user-18669231-0.k.db.ondigitalocean.com:25061,password=AVNS_Y76LkUjnIs1v-ZlA7nv,ssl=True,abortConnect=False"
  REDIS_HOST: "private-criptojackpot-prod-redis-do-user-18669231-0.k.db.ondigitalocean.com"
  REDIS_PORT: "25061"
  REDIS_PASSWORD: "AVNS_Y76LkUjnIs1v-ZlA7nv"
  REDIS_SSL: "true"
