# Secrets for PRODUCTION - DigitalOcean Spaces
apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-spaces-secrets
  namespace: criptojackpot
type: Opaque
stringData:
  SPACES_ENDPOINT: "https://nyc3.digitaloceanspaces.com"
  SPACES_REGION: "nyc3"
  SPACES_BUCKET: "criptojackpot-prod-assets"
  SPACES_ACCESS_KEY: "DO00RAJ79MAZ44LKZAHF"
  SPACES_SECRET_KEY: "jKH9wiMtHNc+6uzB3bdHbZCdgporvHKcrUJ38jWNSmI"
